export const projectLists = [
    {
        img : '/mark1.png',
        title : 'MARK 1',
        desc:'mark 1',
        color: '#ff00ff',
        demo: 'https://replit.com/@AkshayHegde3/mark-1#index.js',
        code: 'https://github.com/AKSHAYHEGDE3/mark-1',
    },
    {
        img : '/mark2.png',
        title : 'MARK 2',
        desc:'mark 2',
        color: '#ff00ff',
        demo: 'https://replit.com/@AkshayHegde3/mark-2#index.js',
        code: 'https://github.com/AKSHAYHEGDE3/mark-2',
    },
    {
        img : '/translation.png',
        title : 'Fun Translation',
        desc:`want to know how yoda and minions will say.write texts in english and it will be translated in their languages`,
        color: '#ff00ff',
        demo: 'https://fun-translation-3.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/fun-translation',
    },
    {
        img : '/recom.png',
        title : 'RECOMMENDATION CENTER',
        desc:'are you bored?,want something good to binge watch,these are some of the recommendations',
        color: '#ff00ff',
        demo: 'https://entertainment-recommendations.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/recommendation-center',
    },
    {
        img : '/emoji.png',
        title : 'EMOJI',
        desc:'want to know meaning of certain emojis! use this',
        color: '#ff00ff',
        demo: 'https://emoji-meaning-3.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/emoji-meaning',
    },
    {
        img : '/cash.png',
        title : 'CASH REGISTER',
        desc:'A register to manage payment.',
        color: '#ff00ff',
        demo: 'https://cash-register-manager-333.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/cash-register',
    },
    {
        img : '/lucky.png',
        title : 'LUCKY BIRTHDAY',
        desc:'check your birthday is lucky by checking your birthday date and lucky number',
        color: '#50C878',
        demo: 'https://lucky-birthday-3.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/lucky-birthday',
    },
    {
        img : '/quiz.png',
        title : 'LEARN TRIANGLES',
        desc:'this website will help you learn about triangles',
        color: '#50C878',
        demo: 'https://learn-triangles-333.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/Learn-Triangles',
    },
    {
        img : '/profit.png',
        title : 'PROFIT OR LOSS',
        desc:'A website which helps you to know how much profit/loss you are making in absolute value as well as percentage',
        color: '#50C878',
        demo: 'https://profit-loss-3.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/profit-loss',
    },
    {
        img : '/palindrome.png',
        title : 'PALINDROME BIRTHDAY',
        desc:'you can check if your birthfday is palindrome or not and if not then from how many days you missed it',
        color: '#50C878',
        demo: 'https://palindrome-birthday-3.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/palindrome-birthday',
    },
    {
        img : '/bingeflix.png',
        title : 'BINGEFLIX',
        desc:'A web Apllication to watch movies,series and animes.Used MERN stack , jwt.',
        color: '#50C878',
        demo: 'https://bingeflix-webapp.herokuapp.com/',
        code: 'https://github.com/AKSHAYHEGDE3/bingeflix',
    },
    {
        img : '/clothify.png',
        title : 'CLOTHIFY',
        desc:'A E-com web application with features like cart,payemnt gateway etc.',
        color: '#2874f0',
        demo: 'https://clothify-24cd7.web.app/',
        code: 'https://github.com/AKSHAYHEGDE3/clothify',
    },
    {
        img : '/yatagram.png',
        title : 'YATAGRAM',
        desc:'A social media web apllication bound to college users.Used MERN stack , jwt, socket io.',
        color: '#ffc107',
        demo: 'https://yatagram.herokuapp.com/',
        code: 'https://github.com/AKSHAYHEGDE3/yatagram',
    },
    {
        img : '/portfolio.png',
        title : 'PORTFOLIO',
        desc:'My portfolio website using next js and tailwind',
        color: '#f9826c',
        demo: 'https://akshay-hegde.vercel.app/',
        code: 'https://github.com/AKSHAYHEGDE3/portfolio',
    },
    {
        img : '/chatsapp.png',
        title : 'CHATSAPP',
        desc:'A real time chat Apllication using Next Js and Firebase.',
        color: '#efeae2',
        demo: 'https://chatsapp-akshay.vercel.app/',
        code: 'https://github.com/AKSHAYHEGDE3/chatsapp',
    },
    {
        img : '/muscify.png',
        title : 'MUSCIFY',
        desc:'A song recommendation web app using React js, Flask, Mongodb,pickle, Machine learning',
        color: '#50C878',
        demo: 'https://github.com/Tejas021/Song_recommendation_system',
        code: 'https://github.com/Tejas021/Song_recommendation_system',
    },
    {
        img : '/rps.png',
        title : 'ROCK PAPER SCISSOR',
        desc:'A rock paper scissor game using html,css ,js',
        color: '#1e5f74',
        demo: 'https://rock-paper-scissors-3.netlify.app',
        code: 'https://github.com/AKSHAYHEGDE3/rock-paper-scissors',
    },
    
]

export const skills = [
    "HTML","CSS","Javascript",'React Js','Next Js',
    'Node js','React Native','Express Js','MongoDB',
    'Python','Firebase'
]